name: Artifact Request CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout PR code
      - uses: actions/checkout@v4

      - name: Run CI checks
        run: |
          echo "build output" > build.txt

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-file
          path: build.txt

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-file

      - name: Use artifact
        run: |
          cat build.txt
          
  

