# Ø§Ø³Ù… Ø§ÛŒÙ† workflow (Ø¯Ø± UI Ú¯ÛŒØªâ€ŒÙ‡Ø§Ø¨ Ù…ÛŒâ€ŒØ¨ÛŒÙ†ÛŒ)
name: Junior DevOps CI

# Ù…Ø´Ø®Øµ Ù…ÛŒâ€ŒÚ©Ù†ÛŒÙ… Ú†Ù‡ Event Ù€ÛŒ workflow Ø±Ùˆ Ø§Ø¬Ø±Ø§ Ú©Ù†Ù‡
on:
  push:          # Ù‡Ø± push Ø¨Ù‡ repo

# ØªØ¹Ø±ÛŒÙ job Ù‡Ø§
jobs:
  hello-ci:      # Ø§Ø³Ù… job (Ø¯Ù„Ø®ÙˆØ§Ù‡)
    
    # Ø±ÙˆÛŒ Ú†Ù‡ Ø³ÛŒØ³ØªÙ…ÛŒ Ø§Ø¬Ø±Ø§ Ø´ÙˆØ¯
    runs-on: ubuntu-latest

    # Ù…Ø±Ø§Ø­Ù„ Ø§Ø¬Ø±Ø§ÛŒÛŒ job
    steps:
      
      # Ù…Ø±Ø­Ù„Ù‡ 1: Ú©Ø¯ repo Ø±Ùˆ Ù…ÛŒâ€ŒÚ©Ø´Ù‡ Ø¯Ø§Ø®Ù„ runner
      - name: Checkout repository
        uses: actions/checkout@v4

      # Ù…Ø±Ø­Ù„Ù‡ 2: Ø§Ø¬Ø±Ø§ÛŒ Ø¯Ø³ØªÙˆØ± shell
      - name: Say Hello
        run: echo "Hello from DevOps CI ğŸš€"
